In [1]:
import numpy as np

In [2]:
a = np.array([[4],[3]])
b = np.array([[-1],[0],[1]])
c = np.array([[2],[1],[3]])
d = np.array([[0],[0]])
e = np.array([[2]])
A = np.array([[2,1],[2,0],[-1,3]])
B = np.array([[3,2,0],[1,0,1],[-2,0,4]])
C = np.eye(3, dtype=int)
D = np.array([[2,1],[1,1]])
E = np.array([[2,3],[2,1]])
F = np.array([[2,3,1],[2,1,4],[3,1,3]])

In [3]:
b+c

array([[1],
       [1],
       [4]])

In [4]:
a+b

ValueError: operands could not be broadcast together with shapes (2,1) (3,1) 

In [5]:
a+d

array([[4],
       [3]])

In [6]:
3*d

array([[0],
       [0]])

In [7]:
2*b

array([[-2],
       [ 0],
       [ 2]])

In [8]:
e@b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

In [9]:
e*b

array([[-2],
       [ 0],
       [ 2]])

In [10]:
# Test how Python read e. Create a 2x1 vector and multiply it by a 4x1 vector:
u = np.array([[2],[1]])
v = np.array([[2],[2],[1],[1]])
u*v

ValueError: operands could not be broadcast together with shapes (2,1) (4,1) 

In [11]:
b@e

array([[-2],
       [ 0],
       [ 2]])

In [12]:
b*e

array([[-2],
       [ 0],
       [ 2]])

In [13]:
a@b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

In [14]:
a*b

ValueError: operands could not be broadcast together with shapes (2,1) (3,1) 

In [15]:
#(a.T)@b
print(a.T)

[[4 3]]


In [16]:
b*c

array([[-2],
       [ 0],
       [ 3]])

In [17]:
(b.T)*(c.T)

array([[-2,  0,  3]])

In [18]:
((b.T)*(c.T)).T

array([[-2],
       [ 0],
       [ 3]])

In [19]:
(b.T)@c

array([[1]])

In [20]:
np.dot(b,c)

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [21]:
np.dot(b.T,c)
print(b.T)
print(c)
np.outer(c,b.T)
#c*b.T

[[-1  0  1]]
[[2]
 [1]
 [3]]


array([[-2,  0,  2],
       [-1,  0,  1],
       [-3,  0,  3]])

In [22]:
(c.T)@b

array([[1]])

In [23]:
b@(c.T)

array([[-2, -1, -3],
       [ 0,  0,  0],
       [ 2,  1,  3]])

In [24]:
a@(b.T)

array([[-4,  0,  4],
       [-3,  0,  3]])

In [25]:
b@(a.T)

array([[-4, -3],
       [ 0,  0],
       [ 4,  3]])

In [26]:
A@a

array([[11],
       [ 8],
       [ 5]])

In [27]:
A@b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [28]:
(b.T)@A

array([[-3,  2]])

In [29]:
B@a

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [30]:
B@b

array([[-3],
       [ 0],
       [ 6]])

In [31]:
A@d

array([[0],
       [0],
       [0]])

In [32]:
B@d

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [33]:
B@e

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

In [34]:
B*e

array([[ 6,  4,  0],
       [ 2,  0,  2],
       [-4,  0,  8]])

In [35]:
A@C

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [36]:
C@A

array([[ 2,  1],
       [ 2,  0],
       [-1,  3]])

In [37]:
B@C

array([[ 3,  2,  0],
       [ 1,  0,  1],
       [-2,  0,  4]])

In [38]:
C@B

array([[ 3,  2,  0],
       [ 1,  0,  1],
       [-2,  0,  4]])

In [39]:
B*C

array([[3, 0, 0],
       [0, 0, 0],
       [0, 0, 4]])

In [40]:
((b.T)@B)@c

array([[0]])

In [41]:
(b.T)@(B@c)

array([[0]])

In [42]:
(b.T)@B@c

array([[0]])

In [43]:
((b-c).T)@A

array([[-6, -9]])

In [44]:
(b.T)@A@a

array([[-6]])

In [45]:
np.linalg.norm(a,2)

5.0

In [46]:
np.linalg.norm(b,2)

1.4142135623730951

In [47]:
np.sqrt((b.T)@b)

array([[1.41421356]])

In [48]:
np.linalg.norm(b,1)

2.0

In [49]:
np.linalg.norm(c,np.inf)

3.0

In [50]:
np.linalg.norm(d,1)

0.0

In [51]:
np.linalg.norm(d,2)

0.0

In [52]:
np.linalg.norm(d,np.inf)

0.0

In [53]:
np.linalg.norm(e,1)

2.0

In [54]:
np.linalg.norm(e,2)

2.0

In [55]:
np.linalg.norm(e,np.inf)

2.0

In [56]:
np.linalg.norm(a,2)*B

array([[ 15.,  10.,   0.],
       [  5.,   0.,   5.],
       [-10.,   0.,  20.]])

In [57]:
B*np.linalg.norm(a,2)

array([[ 15.,  10.,   0.],
       [  5.,   0.,   5.],
       [-10.,   0.,  20.]])

In [58]:
np.linalg.norm(b,np.inf)*B

array([[ 3.,  2.,  0.],
       [ 1.,  0.,  1.],
       [-2.,  0.,  4.]])

In [59]:
np.linalg.inv(D)

array([[ 1., -1.],
       [-1.,  2.]])

In [60]:
np.linalg.inv(C)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
D@np.linalg.inv(D)

array([[1., 0.],
       [0., 1.]])

In [62]:
np.linalg.inv(D)@D

array([[1., 0.],
       [0., 1.]])

In [63]:
np.linalg.eig(D)

(array([2.61803399, 0.38196601]),
 array([[ 0.85065081, -0.52573111],
        [ 0.52573111,  0.85065081]]))

In [64]:
np.linalg.eig(C)

(array([1., 1., 1.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [65]:
np.linalg.eig(E)

(array([ 4., -1.]),
 array([[ 0.83205029, -0.70710678],
        [ 0.5547002 ,  0.70710678]]))

In [66]:
np.linalg.eig(F)

(array([ 6.64123811+0.j        , -0.32061906+1.46827055j,
        -0.32061906-1.46827055j]),
 array([[ 0.52215482+0.j        ,  0.67081734+0.j        ,
          0.67081734-0.j        ],
        [ 0.60869248+0.j        , -0.39917726+0.42379475j,
         -0.39917726-0.42379475j],
        [ 0.5973674 +0.j        , -0.35917974-0.28644291j,
         -0.35917974+0.28644291j]]))

In [67]:
np.dot(a.T,np.array([[1],[0]]))

array([[4]])

In [68]:
(a.T)@np.array([[1],[0]])

array([[4]])

In [69]:
((b.T)@c)/np.linalg.norm(c,2)

array([[0.26726124]])

In [70]:
((c.T)@b)/np.linalg.norm(c,2)

array([[0.26726124]])

In [71]:
((c.T)@b)/np.linalg.norm(b,2)

array([[0.70710678]])

In [72]:
((d.T)@a)/np.linalg.norm(a,2)

array([[0.]])

In [73]:
((d.T)@a)/np.linalg.norm(d,2)

/home/theodore/opt/continuum/miniconda/miniconda3/envs/jupyterlab/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan]])

In [74]:
np.multiply(b,c)

array([[-2],
       [ 0],
       [ 3]])

In [75]:
b*c

array([[-2],
       [ 0],
       [ 3]])

In [76]:
np.outer(b,c)
#np.size(c)
#print(b)
#print(c)
#b@c.T

array([[-2, -1, -3],
       [ 0,  0,  0],
       [ 2,  1,  3]])

In [77]:
b

array([[-1],
       [ 0],
       [ 1]])

In [78]:
c

array([[2],
       [1],
       [3]])